---
# file: main.yml

- name: Create docs project
  k8s:
    name: docs
    api_version: v1
    kind: Namespace
    state: present

- name: change to docs project in oc
  shell: oc project docs

- name: create manifests
  template:
    src: "{{ role_path }}/templates/manifest.yml.j2"
    dest: "{{ role_path }}/files/manifests/{{ item.id }}.yml"
  loop: "{{ workshop_manifests }}"

- name: create configMap from manifests
  shell: "oc create configmap manifests --from-file={{ role_path }}/files/manifests"

- name: Create httpd application
  k8s:
    state: present
    definition: "{{ lookup('file', 'httpd.yml') }}" 

- name: get list of manifest filenames on this machine
  command: ls {{ role_path }}/files/manifests
  register: dir_out

- name: Deploy workshopper application
  k8s:
    state: present
    definition: "{{ lookup('template', 'workshopper.yml.j2') }}"

- name: Get route to workshopper application
  shell: "oc get route devex --template='{{ '{{' }} .spec.host {{ '}}' }}'"
  register: workshopper_route

- name: Create username-distribution project
  k8s:
    name: username-distribution
    api_version: v1
    kind: Namespace
    state: present

- name: change to username-distribution project in oc
  shell: oc project username-distribution

- name: create project template locally from jinja template
  template:
    src: "{{ role_path }}/templates/username-distribution.yml.j2"
    dest: "{{ role_path }}/files/username-distribution.yml"

- name: Deploy username-distribution application
  shell: "oc new-app --file={{ role_path }}/files/username-distribution.yml"

- name: Get route to username-distribution application
  shell: "oc get route username-distribution --template='{{ '{{' }} .spec.host {{ '}}' }}'"
  register: username_route

- debug:
    msg: "Here is the URL for the starting point: https://{{ username_route.stdout }}"